@OpenX.Gest.Api_HostAddress = http://localhost:5064

GET {{OpenX.Gest.Api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{OpenX.Gest.Api_HostAddress}}/weatherforecast/
Accept: application/json

###
