<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <Title>OpenX.Gest.Application.UnitTests</Title>
        <Product>OpenX.Gest.Application.UnitTests</Product>
        <Description>OpenX.Gest.Application.UnitTests</Description>
        <PackageId>OpenX.Gest.Application.UnitTests</PackageId>
        <RootNamespace>OpenX.Gest.Application.UnitTests</RootNamespace>
        <AssemblyName>OpenX.Gest.Application.UnitTests</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.11.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\OpenX.Gest.Domain\OpenX.Gest.Domain.csproj" />
    <ProjectReference Include="..\..\src\OpenX.Gest.Application\OpenX.Gest.Application.csproj" />
    <ProjectReference Include="..\..\src\OpenX.Gest.Infrastructure\OpenX.Gest.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\OpenX.Gest.Api\OpenX.Gest.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="5.0.0" />
    <PackageReference Update="Roslynator.CodeFixes" Version="5.0.0" />
  </ItemGroup>

</Project>