<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>6e7a4f42-bf5f-4ee8-a370-540dd188d816</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenX.Gest.Api\OpenX.Gest.Api.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="5.0.0" />
    <PackageReference Update="Roslynator.CodeFixes" Version="5.0.0" />
  </ItemGroup>

</Project>
