<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <Title>OpenX.Gest.Infrastructure</Title>
      <Product>OpenX.Gest.Infrastructure</Product>
      <Description>OpenX.Gest.Infrastructure</Description>
      <PackageId>OpenX.Gest.Infrastructure</PackageId>
      <RootNamespace>OpenX.Gest.Infrastructure</RootNamespace>
      <AssemblyName>OpenX.Gest.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenX.Gest.Application\OpenX.Gest.Application.csproj" />
    <ProjectReference Include="..\OpenX.Gest.Domain\OpenX.Gest.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="11.0.0-rc.1.26425.128" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="5.0.0" />
    <PackageReference Update="Roslynator.CodeFixes" Version="5.0.0" />
  </ItemGroup>

</Project>
